### ISSUE TITLE
GET team API progress, subject 필터링 추가

### ISSUE THREAD

**Issue by atimangel** [Matching42/Matching42-back#103]
## Description

jiwonlee님의 의견으로 만드는 리팩토링입니다.
end state의 팀이 필요 없을 때가 있어서 백앤드 단에서 end state team을 제외하고 보내게 만들어야합니다.
subject별 팀을 반환하도록 만들어야합니다.

### Todo
- [x] progress = true 라는 쿼리가 들어올 시 allTeams에서 end상태의 team 제거
- [x] subject = ""일 때 team.subject가 일치하지 않는 team제거
- [ ] swagger GET /team 문서에 progress, subject 쿼리 추가
- [ ] figma 시퀀스다이어그램 GET /team/{teamID} 문서 progress, subject 쿼리 추가

**Comment by atimangel** [comment]
체크박스 밑에 두 개는 따로 이슈 만들어서 할까요?
