### ISSUE TITLE
post /waitlist에 목표기간 받는 부분 추가

### ISSUE THREAD

**Issue by Lks9172** [Matching42/Matching42-back#114]
### Todo
- [x] post /waitlist에 목표기간 받는 부분 추가
- [x] delete /waitlist 목표기간 삭제 로직 추가
- [x] swagger api문서 수정
