### ISSUE TITLE
구조 관련 예시 작성 및 임시 DB 추가

### ISSUE THREAD

**Issue by seo2im** [Matching42/Matching42-back#12]
## Description
2주기 실질적 코딩작업을 위한 각각 디렉토리에 적절한 예시 추가

### Todo
- [x] route directory: router 미들웨어 최소 사항 작성
- [x] config directory: DB와 연결
- [x] controller directory : 적절한 예시 작성(미정)
