### ISSUE TITLE
공통 라이브러리 작성 : waitlist컬렉션 조회,에러처리 

### ISSUE THREAD

**Issue by Lks9172** [Matching42/Matching42-back#126]
## Description
공통적으로 사용되는 `대기 리스트 조회 및 에러처리` 에 대한 부분을 라이브러리 함수로 구현

### Todo
- [x] `대기 리스트 조회 및 에러처리` 에 대한 부분을 라이브러리 함수로 구현
- [x] lib/index.tsx에 작성한 공통모듈 export하기
- [x] tWaitlist 타입에 subjectName가 빠져있어 수정
- [x] post /waitlist api에 공통모듈 적용
- [x] delete /waitlist api에 공통모듈 적용
