### ISSUE TITLE
Matcher 코드 개선

### ISSUE THREAD

**Issue by atimangel** [Matching42/Matching42-back#140]
### Todo
- [x] 조건문 좀 더 명시적으로 작성
- [x] 매칭 해야할 서브젝트 필터링 개선
- [x] 매칭에 필요한 인자 원래 변수에서 waitlist.user로 옮기기
- [x] 선호 클러스터 불러오는 방식 수정
- [x] 업데이트 후 객체 반환이 필요 없으므로 findOneAnd계열 외에 다른 함수 사용하기 
      update함수는 지원 종료 된 것으로 보임 
- [x] Team 생성 부분 함수로 만들기

**Comment by atimangel** [comment]
- [ ] git 링크 생성 함수 사용
- [ ] notion page생성함수 사용
- [ ] slack초대장 발송함수 사용
- [ ] mongoDB메소드 사용해서 우선순위 정렬하기

**Comment by atimangel** [comment]
1분에 한 번씩 매칭하도록 스케쥴을 예약해서 테스트해봤습니다. DB에 업데이트 하지 않고 테스트 했습니다.
1분에 한 번씩 매칭 잘되는 거 확인했습니다.
