### ISSUE TITLE
refactoring: post /waitlist 코드 개선

### ISSUE THREAD

**Issue by Lks9172** [Matching42/Matching42-back#141]
### Todo
- [x] findOneUser 공통모듈 적용하기
- [x] map메소드와 include메소드 사용하여 user중복 대기 확인 로직 개선하기
- [x] Error처리 함수 분리하기
- [x] 몽구스 메소드 형식 통일
