### ISSUE TITLE
refactor: delete /waitlist api 리팩토링

### ISSUE THREAD

**Issue by Lks9172** [Matching42/Matching42-back#146]
### Todo
- [x] findOneUser[공통모듈] 적용하기
- [x] 문자열 리터럴 적용하기
- [x] 몽구스 메소드 형식 통일하기
- [x] 에러처리 함수화하기
- [x] map,indexof메소드사용하여 유저가 매칭 대기열에 있는지 확인하는 로직 가독성 향상
