### ISSUE TITLE
PATCH /team/{teamId} 컨트롤러 작성

### ISSUE THREAD

**Issue by hokim2407** [Matching42/Matching42-back#15]
## Description
teamId에 해당하는 팀의 상태를 변경하는 컨트롤러 작성
parameter: { "key" : "변경 state"} 으로 날아온 상태로 팀의 상태를 변경
### Todo
- [x] mongodb 환경 구성
- [x] teamId로 해당 팀의 데이터 불러오기
- [x] 데이터베이스에서 해당 팀의 상태를 변경
- [x] 결과를 클라이언트로 전달

**Comment by hokim2407** [comment]
### Todo
- [] API response에 대해 알아보고 반환 데이터 수정

**Comment by seo2im** [comment]
PR이 변경되면 연결된 PR을 변경해주셔야 합니다. 다음부터는 부탁드리겠습니다

**Comment by seo2im** [comment]
conflict 해결 요청
