### ISSUE TITLE
유저 조회 API 컨트롤러 분리 작업 및 리팩토링

### ISSUE THREAD

**Issue by hminn** [Matching42/Matching42-back#152]
## Description
현재, 유저 조회 시에 userId 라우터 매개변수에 따라 하나의 컨트롤러에서
유저 전체 조회 / 특정 유저 조회가 이루어지도록 작성되어있는 상태입니다.

이에 대해 유저 전체 조회 / 특정 유저 조회 API 컨트롤러를 분리하여 구성하려고 합니다.
동시에 해당 API에 대한 리팩토링 작업도 진행할 예정입니다.

### Todo
- [x] 유저 전체 조회 / 특정 유저 조회 API 분리하기
- [x] API 컨트롤러 코드 리팩토링
- [x] Swagger API 문서 수정
