### ISSUE TITLE
User DB Model 정의

### ISSUE THREAD

**Issue by hminn** [Matching42/Matching42-back#16]
## Description
User 에 대한 DB Modeling 을 진행한다.

### Todo
- [x] User DB Model 정의
- [x] User의 intraInfo 속성에 대한 논의 진행
- [x] 논의 결과 반영하여 스키마 수정

**Comment by seo2im** [comment]
assign은 해당 이슈의 담당자이므로 저를 할당안하셔도 되고 PR을 생성하실 때, reviewer를 저로 설정해주시면 됩니다

**Comment by hminn** [comment]
회의 내용 반영하여 수정 완료했습니다.
확인 부탁드리겠습니다.
