### ISSUE TITLE
Team DB model 모델 정의

### ISSUE THREAD

**Issue by atimangel** [Matching42/Matching42-back#17]
## Description
몽고 DB를 활용해 team DB 모델 설계
### Todo
- [x] 몽구스 훑어보기
- [x] DB 예시를 체크하기.
- [x] 몽구스 예시 따라 만들어보기
- [ ] 아틀라스 uri를 통해 연결된 파일 만들기
- [ ] team 스키마 만들기

**Comment by seo2im** [comment]
milestone을 등록 안하셨습니다. milestone 2주기로 설정 부탁드립니다

**Comment by seo2im** [comment]
제 url이 올라가면 절대 안됩니다!!!!!!!!! 제 비밀번호가 고스란히 노출됩니다
아래 2개의 글을 참고하여 설정을 변경해 주세요. 반드시 .gitignore도 등록해주셔야 합니다.

commit history 삭제법: https://jjjoonngg.github.io/git/Git-History/
**반드시 마지막의 `--all`은 본인 branch 이름으로 변경해주세요**
dotenv 사용하여 secret 관리: https://hudi.kr/node-js-dotenv-%ED%99%98%EA%B2%BD-%EB%B3%80%EC%88%98-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0/

**Comment by atimangel** [comment]
죄송합니다 얼른 지우겠습니다

**Comment by atimangel** [comment]
DB uri 있던 파일 커밋 히스토리에서 삭제했습니다.

--all하면서 위험할 텐데란 생각은 했는데 역시... 제 브랜치에서만 지우고 푸쉬하는 거였네요.
아래는 명령어가 잘 안먹어서 저런 파일명 없겠지 싶어서 그대로 실행해봤는데 rewrittern이 떠서 로그 올려봅니다. 
나머지는 모든 브랜치에서 unchanged가 뜨거나, 제 브랜치만 rewritten이 떠서 영향이 없는 것 같습니다.
영향을 안받은 feature/#14랑 development 브랜치 커밋을 비교해봤을 때 커밋 개수 차이는 없었습니다. 그래서 다행히 별 문제 없지 않을까 싶은데... 암튼 사고쳐서 죄송합니다.

snpark@mmui-Macmini Matching42-back % git filter-branch -f --index-filter 'git rm --cached --ignore-unmatch 삭제하고자하는 file명' --prune-empty -- --all
WARNING: git-filter-branch has a glut of gotchas generating mangled history
	 rewrites.  Hit Ctrl-C before proceeding to abort, then use an
	 alternative filtering tool such as 'git filter-repo'
	 (https://github.com/newren/git-filter-repo/) instead.  See the
	 filter-branch manual page for more details; to squelch this warning,
	 set FILTER_BRANCH_SQUELCH_WARNING=1.
Proceeding with filter-branch...

Rewrite c6a947e9206fa3261d427bc1f21ae3dda4fd6f51 (1/18) (0 seconds passed, reRewrite 59928b0a8196040e259fe250c5958b0b00f5035a (2/18) (0 seconds passed, reRewrite 1fcf312bc07d21143679888c300e89945b2fd50a (3/18) (0 seconds passed, reRewrite 6bef7262d169dbf931a0669a00702ebc2566edf8 (4/18) (0 seconds passed, reRewrite 54c8ccb3cbeb9c850bfa61afa56b079cb3087909 (5/18) (0 seconds passed, reRewrite 257646574684cb0994d3234dec735d8ef0dd8f57 (6/18) (0 seconds passed, reRewrite 2992c20288db53d65011dbd5a4e927847b2af18b (7/18) (0 seconds passed, reRewrite 65fe61317a5a9f888b7e2230153a2774c795f408 (8/18) (0 seconds passed, reRewrite e070cb3e252b7efcf4845963b5aa1fd9e7d61f88 (9/18) (0 seconds passed, reRewrite b0cfec280171e50d60a6a01396b7dfbecdb85308 (10/18) (0 seconds passed, rRewrite 1ae2ed6c7b8011096a4f0960bdfdd85fee9a5ca4 (11/18) (0 seconds passed, rRewrite 42b37d0daaa8cd84605a7fb2919b8b29a2c1e58e (12/18) (0 seconds passed, rRewrite cd74406e183b0472efcc0a785ca569b774c7d537 (13/18) (0 seconds passed, rRewrite 512fda4f666dcf94b3af5e72e1d66c0e5ad250ea (14/18) (0 seconds passed, rRewrite e4564c78fbbad8b5f4499c3c8f5b226ef25908ca (15/18) (0 seconds passed, rRewrite b24f4c2430aac224d6cb671f4fcc05fb63f623d5 (16/18) (0 seconds passed, rRewrite 6079d34ff63cf88823366b077000027a1ed7d36f (17/18) (0 seconds passed, rRewrite c2b5e15d4e23117d7930db919332af197e2563f6 (18/18) (0 seconds passed, remaining 0 predicted)
Ref 'refs/heads/development' was rewritten
Ref 'refs/heads/feature/#17' was rewritten
Ref 'refs/remotes/origin/development' was rewritten
