### ISSUE TITLE
AWS 배포 빌드 스펙 작성

### ISSUE THREAD

**Issue by Lks9172** [Matching42/Matching42-back#173]
### Todo
- [x] server EC2 인스턴스 생성
- [x] server ec2 인스턴스에서 nginx설정 및 node server 백그라운드 실행
- [x] 도메인 등록 및 nginx사용하여 https적용하기
- [x] github actions + aws s3 + aws codedeploy를 사용하여 CI/CD 파이프라인 정의하기
- [x] CI -  코딩컨벤션 검사(eslint) + 빌드 
- [ ] 환경 변수 관리
