### ISSUE TITLE
유저 스키마에 유저의 과거 팀 리스트 필드를 추가

### ISSUE THREAD

**Issue by hminn** [Matching42/Matching42-back#189]
## Description
- 프론트 팀에서 MyTeamView에 유저의 과거 팀들도 렌더링 할 필요성을 느껴 이에 대한 요청 사항이 들어옴
- NoSQL의 한계 때문에 유저의 과거 팀을 조회하기가 불편한 상황 
(조회 시, 팀 데이터 중 state가 end면서 memberID에 해당 유저가 포함되어 있는 데이터만 필터링을 해야하는 상황)
- DB 조회에 대한 부담을 줄이고자, 유저 스키마에 유저의 과거 팀을 저장할 필드를 만들어 담아주는 방향으로 진행

### Todo
- [x] 유저 스키마에 과거 팀 리스트 필드를 추가
- [x] tUser 타입 객체 최신화
- [x] Swagger 문서 최신화
