### ISSUE TITLE
aws instance 변경 관련 ci/cd test와 수정

### ISSUE THREAD

**Issue by Lks9172** [Matching42/Matching42-back#206]
## Description
aws instance 변경 관련 ci/cd test와 수정

### Todo

- [x] ec2 instance t2.xlarge로 업그레이드
- [x] ci/cd 의 배포 인스턴스도 새로운 인스턴스로 변경
- [x] https 적용
- [x] codedeploy 작업시에 인스턴스 자원 부족으로 중지되던 문제 인스턴스 업그레이드로 해결
