### ISSUE TITLE
AWS 아키텍처 개선 및 다이어그램 작성

### ISSUE THREAD

**Issue by hminn** [Matching42/Matching42-back#208]
## Description
프로젝트의 현 AWS 아키텍처 구성을 파악하고, 문제점을 찾아 개선한다.
개선된 AWS 아키텍처의 다이어그램을 작성하고, 문서화를 진행한다.

### Todo
- [x] 현재 AWS 아키텍처 구성 파악
- [ ] 문제점 파악 및 개선
- [ ] AWS 아키텍처 다이어그램 작성 툴 선정
- [ ] AWS 아키텍처 다이어그램 작성
- [ ] 개선된 AWS 아키텍처에 대한 문서화
