### ISSUE TITLE
유저 정보 갱신 API 구현

### ISSUE THREAD

**Issue by hminn** [Matching42/Matching42-back#209]
## Description
기존 유저의 정보를 갱신하는 API를 구현한다.

### Todo
- [x] PATCH /user/{userID} 요청 라우팅
- [x] 유저 정보 갱신 API 컨트롤러 로직 구현
- [x] 구현 완료된 API 테스트 진행
- [x] Swagger API 문서 작성
