### ISSUE TITLE
slack 메시지 개인 DM화 작업

### ISSUE THREAD

**Issue by seo2im** [Matching42/Matching42-back#237]
## Description
채널로 보내던 메시지 개인 메시지로 변경

### Todo
- [ ] User DB 수정
- [ ] 가입시 받아오는 기능(아직 넣지 말것)
- [ ] send에서 DB의 memberID 받아오도록 수정
