### ISSUE TITLE
GET /user/{userId} 컨트롤러 작성

### ISSUE THREAD

**Issue by hminn** [Matching42/Matching42-back#24]
## Description
userId에 해당하는 유저 정보를 조회하는 컨트롤러 작성
userId가 없으면 모든 유저 데이터를 반환

### Todo
- [x] express에 MVC 패턴 적용 학습
- [x] 라우터, 컨트롤러 관련 학습
- [x] '/user', '/user/{userId}' 에 대한 라우팅 작업
- [x] mongodb 환경 구성
- [x] userId를 넘겨주면 해당 유저 데이터 불러오기
- [x] 유저 데이터 클라이언트로 전달 (조회 실패시 결과 전달)
