### ISSUE TITLE
GET /team/{teamId} 컨트롤러 작성

### ISSUE THREAD

**Issue by atimangel** [Matching42/Matching42-back#30]
## Description
client에서 GET /team/{teamId} 요청이 왔을 때 컨트롤러 구현
팀 데이터 반환 하는 api
id가 없으면 모든 팀 데이터 반환
### Todo
- [ ] 카카오 api페이지 참고하기
- [ ] 시퀀스 다이어그램과 흐름이 달라질 때 시퀀스 다이어그램 수정
- [x] getUser 컨트롤러 참고하면서 작성중
- [x] 페이지네이션 구현

**Comment by seo2im** [comment]
전통적인 page based pagenation api형태로 구현하겠습니다.
api 형태 /team?page=[number]&limit=[number]

Query
page ⇒ page index
limit ⇒ num of response datas(teams) => default는 5로 고정

example> /team?page=1&limit=5
team 데이터 5 ~ 9번까지 반환
example> /team (아무것도 없는경우)
team 데이터 0 ~ 5번까지 반환
example> /team?limit=10
team 데이터 0 ~ 10번까지 반환
example> /team?page=2
team 데이터 10 ~ 14번까지 반환

참고 link

프론트엔드 쪽에서 아래 구성을 이용해서 무한 스크롤을 구현할 예정이니 참고바랍니다
swr pagination api handling link

**Comment by atimangel** [comment]
mongoose.prototype.schema.findId 가 있긴한데 _id형식으로 되어있는 걸 찾는 거여서 findOne이나 find를 써야겠네요.

**Comment by atimangel** [comment]
문제사항 기록 

- 2c9e73f7821b394fd9aa44acec79224cdf231b3e 이 커밋은 아직 테스트 해보지 않았음
- 팀 데이터에 배열처럼 인덱스가 붙어있는 건가요? 일단 아틀라스에서 확인해보려고 합니다.
- get /team?limit=10 이런식으로 요청시 req.params.limit로 받을 수 있는 것인지 궁금합니다.
-

**Comment by atimangel** [comment]
더미 데이터 ID가 숫자 오름차순으로 되어 있는데 0~4번째 데이터를 찾고자하면, ID를 사용해서 불러오면 되는 걸까요?

**Comment by seo2im** [comment]
> 문제사항 기록
> 
> * [2c9e73f](https://github.com/Matching42/Matching42-back/commit/2c9e73f7821b394fd9aa44acec79224cdf231b3e) 이 커밋은 아직 테스트 해보지 않았음
> * 팀 데이터에 배열처럼 인덱스가 붙어있는 건가요? 일단 아틀라스에서 확인해보려고 합니다.
> * get /team?limit=10 이런식으로 요청시 req.params.limit로 받을 수 있는 것인지 궁금합니다.

req.query로 받을 수 있습니다.
query와 param의 차이를 조사해보세요

**Comment by seo2im** [comment]
> 더미 데이터 ID가 숫자 오름차순으로 되어 있는데 0~4번째 데이터를 찾고자하면, ID를 사용해서 불러오면 되는 걸까요?

안됩니다. 만약 중간의 정보가 삭제된다면 해당 공간은 빈것이 될 테니까요. 해당 데이터 컬럼에 대해 접근하는 방법을 확인해보시면 됩니다
[참고](https://velog.io/@won-developer/Node.js-mongoose-%ED%8E%98%EC%9D%B4%EC%A7%95-%EA%B8%B0%EB%8A%A5-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0)
