### ISSUE TITLE
API 문서 작성

### ISSUE THREAD

**Issue by hminn** [Matching42/Matching42-back#37]
## Description
[Gitbook - Matching42 API Documentation](https://app.gitbook.com/@matching42/spaces)
GET /user/{userId} API 문서 작성
POST /addmember API 문서 작성

### Todo
- [x] Kakao API 문서 참고하여 형식 파악
- [x] GET /user/{userId} API 문서 작성
- [x] POST /addmember API 문서 작성
- [x] 오타 수정 및 문서 구체화
- [ ] 문제 사항 피드백

### 문제 사항
- getUser 반환 데이터 중 유저 정보 필드명이 현재 `data` 로 되어있는데 `user` 가 더 적절할 것 같습니다.
- team 모델 스키마에 `required(필수)` 옵션이 필요한 필드가 있습니다.
=> ID, leaderID, memberID, subject, state...
- 팀 state에서 `less_member` 에 대한 설명이 불명확합니다.
- 포스트맨으로 API 테스트 진행 시, userId를 인식하지 못하는 문제 발생 (getUser, addMember API 대상으로 테스팅)
=> 리팩토링 과정 중, addMember를 addUser2Team으로 변경하는 과정에서 충돌이 발생 (컨트롤러 함수명은 `addMember` 이지만, 컨트롤러 인덱스 파일에서 export 시에는 addUser2Team으로 되어있음)

**Comment by seo2im** [comment]
수정사항 월 회의에서 통합적으로 말씀 드리겠습니다
