### ISSUE TITLE
swagger에 담당 API문서작성

### ISSUE THREAD

**Issue by Lks9172** [Matching42/Matching42-back#47]
### Todo
- [x] Kakao API 문서 참고하여 형식 파악
- [x] swagger에 Waitlist스키마 작성
- [x] POST /waitlist API 문서 작성
- [x]  DELETE /waitlist/{userId} API문서 작성
- [x] 다이어그램 수정

**Comment by seo2im** [comment]
수정사항 월 회의에서 통합적으로 말씀 드리겠습니다

**Comment by Lks9172** [comment]
@seo2im 알겠습니다.
