### ISSUE TITLE
GET team/{teamId} API 문서 작성

### ISSUE THREAD

**Issue by atimangel** [Matching42/Matching42-back#48]
## Description
-팀 데이터를 얻고 싶은 개발자가 API를 사용하면 어떤 데이터를 얻을 수 있는지 예측 가능하게 해주는 문서작성
### Todo
- [x] 팀 스키마
- [ ] 특정 팀의 정보를 얻고 싶을 때
- [ ] 모든 팀의 정보를 얻고 싶을 때
- [ ] 특정 범위의 팀의 정보를 얻고 싶을 때
- [ ] Swagger에 문서 작성

**Comment by atimangel** [comment]
깃북에 작성 할 api문서를 swagger에 적겠습니다.

**Comment by atimangel** [comment]
api테스트 해보려고 했는데, 인증이 필요하게 된 것 같아 나중에 하겠습니다.

**Comment by atimangel** [comment]
GET /team 컨트롤러에 대한 문서가 푸쉬가 안돼서 다른 이슈 열겠습니다.
