### ISSUE TITLE
팀 자동 매칭 시스템 작성

### ISSUE THREAD

**Issue by atimangel** [Matching42/Matching42-back#50]
## Description
매칭 일에 매칭 풀에서 각 서브젝트 별로 팀을 만들어줌
### Todo
- [x] waitList에 있는 데이터 불러오기
- [x] 각 서브젝트 별로 나누기
- [x] 3명이면 팀 만들어주기
- [x] 3명 이하일 때 팀 만들어주기
- [x] 3명 이상일 때 선호 클러스터를 고려해서 팀 매칭
- [x] 만들어진 팀, 팀 DB에 저장하기
- [ ] 새로 매칭 된 팀 이후 작업과 어떻게 연동시켜야할지
- [x] team ID와 teamName은 어떻게 설정해야하는지

**Comment by atimangel** [comment]
@seo2im team 모델에 ID나 teamName은 명명법이 정해져 있나요?

**Comment by seo2im** [comment]
@atimangel 정해진것은 없습니다 중복되지 않도록 직접 만들어주셔도 될것같아요
