### ISSUE TITLE
Login 기능 DB model 문서와 통일 작업 진행

### ISSUE THREAD

**Issue by seo2im** [Matching42/Matching42-back#69]
## Description
현 작업 문서(ver 0.2)와 일치하도록 코드 및 다이어그램 수정
[DB Model 2.0](https://www.notion.so/DB-MODEL-0-2-2d51e05b313c43b5bdc34e3156e13df5)
[API Spec 2.0](https://www.notion.so/API-0-2-457b701e92344053afebfc6f245eb858)

### Todo
- [ ] 코드 변수명 확인 및 통일
- [ ] 시퀀스 다이어그램 핑퐁 재작성(Auth 2.0 형태 전체 수정
- [ ] redirect uri check 기능 추가
