### ISSUE TITLE
[fix] 시퀀스다이어그램, API문서, 작성코드 네이밍 통일

### ISSUE THREAD

**Issue by Lks9172** [Matching42/Matching42-back#75]
### Todo
- [x] 시퀀스 다이어그램 확인
- [x] API문서 네이밍 확인
- [x] 작성한 API 코드 네이밍 확인
- [x] 작성한 model 네이밍 확인
- [x] Router path, 변수명, 및 swagger문서 에서 userId -> userID로 모두 네이밍 변경

**Comment by seo2im** [comment]
Review 확인

**Comment by seo2im** [comment]
해당 PR unmerged된 상태에서 close되었는데, 정상적인 상황인지 확인 부탁드립니다

**Comment by seo2im** [comment]
다른 이슈 링킹 확인했습니다. 앞으로 이러한 실수 시 간단히 다른 이슈 연결되었다고 언급 부탁드립니다

**Comment by Lks9172** [comment]
> 다른 이슈 링킹 확인했습니다. 앞으로 이러한 실수 시 간단히 다른 이슈 연결되었다고 언급 부탁드립니다

@seo2im 알겠습니다!
