### ISSUE TITLE
GET /waitlist API 구현

### ISSUE THREAD

**Issue by Lks9172** [Matching42/Matching42-back#87]
### Todo
- [x] get /waitlist API구현
- [x] 아래 이미지에서 사용될 총 랜덤매칭대기인원수를 반환

<img width="483" alt="스크린샷 2021-06-23 오후 8 55 00" src="https://user-images.githubusercontent.com/44085243/123092273-476c5700-d465-11eb-976c-8e94b105dbfc.png">

- [x] swagger api문서 작성

**Comment by seo2im** [comment]
conflict 확인
