### ISSUE TITLE
프로젝트 Git setting

### ISSUE THREAD

**Issue by seo2im** [Matching42/Matching42-back#9]
## Description
워크플로우 가이드에 맞추어 github setting 변경

## Todo
- [x] 이슈 template 등록
- [x] commit template 파일 등록
- [x] PR template 적용
- [x] prettier 적용
- [x] 1주기 Issue 정리작업

**Comment by seo2im** [comment]
commit template와 prettier 설정 미수

**Comment by seo2im** [comment]
잘못 Close함

**Comment by seo2im** [comment]
1주기 Issue들 정리 작업 수행 추가
